/*
* File name: Domain.hpp
* Project: KasX Compiler
* Author: Lasantha M Senanayake
* Date created: 2025-12-14 01:49:32
// Date modified: 2026-08-29 14:26:37
* ------
*/

#pragma once

#include <kasx/core/scopes/GlobalScope.hpp>

#include "kasx/Types.hpp"
#include "kasx/core/scopes/Scope.hpp"

namespace KasX::Compiler::Visitors {
class ProgramVisitor;
}

namespace KasX::Compiler::Core {
/**
 * @class Domain
 * @brief This class holds all the data related to the domain, its the entrypoint to all the data and controls all the acccess to
 * the domain data
 */
class Domain {
 public:
  /**
   * @brief Domain constructor
   *
   * @param data DomainData required to initialize the Domain.
   */
  explicit Domain(DomainData& data);
  ~Domain();
  /**
   * @brief Initializes the visitor class generated by the antlr4 generator to visit the domain file.
   */
  void initVisitor();

  /**
   * @brief Initializes default types number, boolean, entity and character types in the global scope.
   */
  void initDefaultTypes();

  /**
   * @brief Getter for the global scope.
   *
   * @return Global scope.
   */
  Scopes::GlobalScope* getGlobalScope() { return &m_GlobalScope; };

  /**
   * @brief Get the currently active scope
   *
   * @return Current scope
   */
  Scopes::Scope* getCurrentScope() const { return m_CurrentScope; };

  /**
   * @brief Set a new scope as current scope
   *
   * @param scope Scope to be set as the current scope
   */
  void setCurrentScope(Scopes::Scope* scope) { m_CurrentScope = scope; }

 private:
  Scopes::Scope* m_CurrentScope;
  Scopes::GlobalScope m_GlobalScope;
  DomainData m_DomainData;
  std::unique_ptr<Compiler::Visitors::ProgramVisitor> m_ProgramVisitor;
};
}  // namespace KasX::Compiler::Core
