/*
* File name: Domain.hpp
* Project: KasX Compiler
* Author: Lasantha M Senanayake
* Date created: 2025-12-14 01:49:32
// Date modified: 2025-12-30 22:04:48
* ------
*/

#pragma once

#include "kasx/Types.hpp"

namespace KasX::Compiler::Visitors {
class ProgramVisitor;
}

namespace KasX::Compiler::Core {
/**
 * @class Domain
 * @brief This class holds all the data related to the domain, its the entrypoint to all the data and controls all the acccess to
 * the domain data
 */
class Domain {
 public:
  /**
   * @brief Domain constructor
   *
   * @param data DomainData required to initialize the Domain.
   */
  explicit Domain(DomainData& data);
  ~Domain();
  /**
   * @brief Initializes the visitor class generated by the antlr4 generator to visit the domain file.
   */
  void initVisitor();

  void initDefaultTypes();

 private:
  DomainData m_DomainData;
  std::unique_ptr<Compiler::Visitors::ProgramVisitor> m_ProgramVisitor;
};
}  // namespace KasX::Compiler::Core
