/*
* File name: ProgramVisitor.hpp
* Project: KasX Compiler
* Author: Lasantha M Senanayake
* Date created: 2025-12-21 14:20:04
// Date modified: 2026-03-19 18:08:47
* ------
*/
#pragma once
#include <any>
#include <kasx/core/logging/TraceableClass.hpp>

#include "AntlrSafeBase.hpp"
#include "KasXParser.h"
#include "kasx/Domain.hpp"
#include "kasx/debug/DomainFileTrace.hpp"

namespace KasX::Compiler::Visitors {
/**
 * @class ProgramVisitor
 * @brief This class will visit the domain context tree generated by antlr4 and port it to this custom visitor class to handle
 * build the domain in KasX compiler program.
 *
 * This class will handle all the visiting of the parse tree created by antlr4
 *
 */
class ProgramVisitor : public KasXBaseVisitor, public Core::TraceableClass {
 public:
  explicit ProgramVisitor(Core::Domain* domain);

  ~ProgramVisitor() override;

  /**
   * @brief Visitor function for the type declaration.
   *
   * @param ctx Type Declaration context
   */
  std::any visitTypeDeclaration(KasXParser::TypeDeclarationContext* ctx) override;

  /**
   * @brief Visitor function for types list (Eg: location, character)
   *
   * @param ctx Types list context
   */
  std::any visitTypesList(KasXParser::TypesListContext* ctx) override;

  /**
   * @brief Visitor function for entity declaration.
   *
   * @param ctx Entity declaration context.
   */
  std::any visitEntityDeclaration(KasXParser::EntityDeclarationContext* ctx) override;

  /**
   * @brief Visitor function for a fluent declaration
   *
   * @param ctx Fluent declaration context
   */
  std::any visitFluentDeclaration(KasXParser::FluentDeclarationContext* ctx) override;

  /**
   * @brief Visitor function for a function header
   *
   * @param ctx Function header context
   */
  std::any visitFunctionHeader(KasXParser::FunctionHeaderContext* ctx) override;

  /**
   * @brief Visitor function for parameter list
   *
   * @param ctx Parameter list context
   */
  std::any visitParamList(KasXParser::ParamListContext* ctx) override;

  /**
   * @brief Visitor function for the parameter
   *
   * @param ctx Parameter context
   */
  std::any visitParam(KasXParser::ParamContext* ctx) override;

 private:
  Core::Domain* m_Domain;

  // ---- Printing messages (Trace)
  static void PrintStartVisit(std::string_view type, std::string_view identifier);

  static void PrintEndVisit(std::string_view type, std::string_view identifier);

  static void EditParentsData(const std::string& typeDeclarationName, std::vector<std::string>& parents);

  static Debug::DomainFileTrace getTraceData(antlr4::Token* startToken, antlr4::Token* endToken);
};
}  // namespace KasX::Compiler::Visitors
