/*
* File name: ProgramVisitor.hpp
* Project: KasX Compiler
* Author: Lasantha M Senanayake
* Date created: 2025-12-21 14:20:04
// Date modified: 2026-08-29 10:33:35
* ------
*/
#pragma once
#include <any>
#include <cstddef>
#include <functional>
#include <kasx/core/logging/TraceableClass.hpp>
#include <vector>

#include "AntlrSafeBase.hpp"
#include "KasXParser.h"
#include "kasx/Domain.hpp"
#include "kasx/data_structures/declarations/EntityDeclaration.hpp"
#include "kasx/data_structures/declarations/helpers/FunctionHeader.hpp"
#include "kasx/data_structures/expressions/Expression.hpp"
#include "kasx/data_structures/expressions/operations/BinaryOperationTypes.hpp"
#include "kasx/data_structures/expressions/operations/IfElseOperation.hpp"
#include "kasx/debug/DomainFileTrace.hpp"

namespace KasX::Compiler::Visitors {
/**
 * @class ProgramVisitor
 * @brief This class will visit the domain context tree generated by antlr4 and port it to this custom visitor class to handle
 * build the domain in KasX compiler program.
 *
 * This class will handle all the visiting of the parse tree created by antlr4
 *
 */
class ProgramVisitor : public KasXBaseVisitor, public Core::TraceableClass {
 public:
  explicit ProgramVisitor(Core::Domain* domain);

  ~ProgramVisitor() override;

  /**
   * @brief Root visitor for the program. Visits definitions in three passes (types/entities, then fluents, then
   * everything else) instead of file order, so that fluent grounding always sees every declared entity regardless
   * of where fluents/actions/triggers/utility declarations appear in the source file.
   *
   * @param ctx Program context (root of the parse tree)
   */
  std::any visitProgram(KasXParser::ProgramContext* ctx) override;

  /**
   * @brief Visitor function for the type declaration.
   *
   * @param ctx Type Declaration context
   */
  std::any visitTypeDeclaration(KasXParser::TypeDeclarationContext* ctx) override;

  /**
   * @brief Visitor function for types list (Eg: location, character)
   *
   * @param ctx Types list context
   */
  std::any visitTypesList(KasXParser::TypesListContext* ctx) override;

  /**
   * @brief Visitor function for entity declaration.
   *
   * @param ctx Entity declaration context.
   */
  std::any visitEntityDeclaration(KasXParser::EntityDeclarationContext* ctx) override;

  /**
   * @brief Visitor function for a fluent declaration
   *
   * @param ctx Fluent declaration context
   */
  std::any visitFluentDeclaration(KasXParser::FluentDeclarationContext* ctx) override;

  /**
   * @brief Visitor function for a function header
   *
   * @param ctx Function header context
   */
  std::any visitFunctionHeader(KasXParser::FunctionHeaderContext* ctx) override;

  /**
   * @brief Visitor function for parameter list
   *
   * @param ctx Parameter list context
   */
  std::any visitParamList(KasXParser::ParamListContext* ctx) override;

  /**
   * @brief Visitor function for the parameter
   *
   * @param ctx Parameter context
   */
  std::any visitParam(KasXParser::ParamContext* ctx) override;

  /**
   * @brief Visitor function for the initial state declaration
   *
   * @param ctx Initial State Declaration state
   */
  std::any visitInitialStateDecl(KasXParser::InitialStateDeclContext* ctx) override;

  /**
   * @brief Not expression visitor function
   *
   * @param ctx Not Expression context
   */
  std::any visitExprNot(KasXParser::ExprNotContext* ctx) override;

  /**
   * @brief Negation expression
   *
   * @param ctx Negation expression context
   */
  std::any visitExprNegation(KasXParser::ExprNegationContext* ctx) override;

  /**
   * @brief Expression in a bracket (just returns whatever inside the brackets as an expression)
   *
   * @param ctx Expression in a bracket context
   */
  std::any visitExprInBracket(KasXParser::ExprInBracketContext* ctx) override;

  /**
   * @brief Binary operation visitor function returns the operation and its operands as Expression
   *
   * @param ctx Binary operation context
   */
  std::any visitExprBinaryOp(KasXParser::ExprBinaryOpContext* ctx) override;

  /**
   * @brief Fluent reference visitor function, eg: path(Castle, Mountain), alive(Aladdin)
   *
   * @param ctx Fluent value context
   */
  std::any visitFluentVal(KasXParser::FluentValContext* ctx) override;

  /**
   * @brief Argument list visitor function (Helper), returns the identifiers as a vector of strings
   *
   * @param ctx Argument list context
   */
  std::any visitArgumentList(KasXParser::ArgumentListContext* ctx) override;

  /**
   * @brief Fluent expression visitor function, delegates to the fluent rule
   *
   * @param ctx Fluent expression context
   */
  std::any visitExprFluent(KasXParser::ExprFluentContext* ctx) override;

  /**
   * @brief Bare identifier expression visitor function, eg: Jafar, Castle
   *
   * @param ctx Identifier expression context
   */
  std::any visitExprIdentifier(KasXParser::ExprIdentifierContext* ctx) override;

  /**
   * @brief Number literal expression visitor function
   *
   * @param ctx Number expression context
   */
  std::any visitExprNumber(KasXParser::ExprNumberContext* ctx) override;

  /**
   * @brief Unknown value ('?') expression visitor function
   *
   * @param ctx Unknown expression context
   */
  std::any visitExprUnknown(KasXParser::ExprUnknownContext* ctx) override;

  /**
   * @brief Believes expression visitor function, delegates to the belives_expression rule
   *
   * @param ctx Believes expression context
   */
  std::any visitExprBelives(KasXParser::ExprBelivesContext* ctx) override;

  /**
   * @brief Believes expression body visitor function, eg: believes(Merchant, at(Tom) = ?)
   *
   * @param ctx Believes expression context
   */
  std::any visitBelives_expression(KasXParser::Belives_expressionContext* ctx) override;

  /**
   * @brief For all expression visitor, (For loop)
   *
   * @param ctx For all expression context
   */
  std::any visitExprForAll(KasXParser::ExprForAllContext* ctx) override;

  /**
   * @brief Visitor function for action declarations
   *
   * @param ctx Action declaration context
   * @return returns nullptr
   */
  std::any visitActionDecl(KasXParser::ActionDeclContext* ctx) override;

  /**
   * @brief Visitor function for trigger declarations
   *
   * @param ctx Trigger delcaration context
   * @return returns nullptr
   */
  std::any visitTriggerDecl(KasXParser::TriggerDeclContext* ctx) override;

  /**
   * @brief Visitor function for utility declarations
   *
   * @param ctx Utility declaration context
   * @return returns nullptr
   */
  std::any visitUtilityDecl(KasXParser::UtilityDeclContext* ctx) override;

  /**
   * @brief Visitor function for if else expressions
   *
   * @param ctx If else expression context
   * @return returns ExpressionPtr
   */
  std::any visitExprIfElse(KasXParser::ExprIfElseContext* ctx) override;

 private:
  Core::Domain* m_Domain;

  // ---- Printing messages (Trace)
  static void PrintStartVisit(std::string_view type, std::string_view identifier);

  static void PrintEndVisit(std::string_view type, std::string_view identifier);

  static void EditParentsData(const std::string& typeDeclarationName, std::vector<std::string>& parents);

  static Debug::DomainFileTrace getTraceData(antlr4::Token* startToken, antlr4::Token* endToken);

  static DataStructures::Expressions::BINARY_OPERATION_TYPES getBinaryOperationType(KasXParser::Binary_opContext* ctx);

  /**
   * @brief Check whether a type declaration is, or inherits from (directly or transitively), a type with the given name.
   * Mirrors Sabre's `Parameter.mustBeCharacter()` check used to validate the first argument of an epistemic expression.
   *
   * @param type Type declaration to check, walking up its parents.
   * @param typeName Name of the type it must be or inherit from, eg: "character"
   */
  static bool typeInheritsFrom(DataStructures::Declarations::TypeDeclaration* type, const std::string& typeName);

  /**
   * @brief Check whether an entity declaration is of (or inherits from) the given type.
   *
   * @param entity Entity declaration to check.
   * @param typeName Name of the type it must be or inherit from, eg: "character"
   */
  static bool entityIsOfType(DataStructures::Declarations::EntityDeclaration* entity, const std::string& typeName);

  void recurseParams(const std::vector<std::vector<DataStructures::Declarations::EntityDeclaration*>>& vecs, size_t depth,
                     std::vector<DataStructures::Declarations::EntityDeclaration*>& current,
                     std::vector<std::vector<DataStructures::Declarations::EntityDeclaration*>>& combinations);

  void getAllEntityDeclFromHeader(const DataStructures::Declarations::Helpers::FunctionHeader& functionHeader,
                                  std::vector<std::vector<DataStructures::Declarations::EntityDeclaration*>>& vecs);

  /**
   * @brief Grounds every parameter combination of a function header against the given scope's replace map and invokes
   * `perCombination` once per combination. Shared by action and trigger declarations, which both ground a function header
   * the same way but build a different kind of grounded declaration out of it.
   *
   * @param functionHeader Function header (name + parameters) to ground.
   * @param scope Scope that owns the replace map to populate for each combination.
   * @param perCombination Callback invoked once per combination, after the scope's replace map has been updated.
   */
  void groundHeaderParameters(const DataStructures::Declarations::Helpers::FunctionHeader& functionHeader,
                              Core::Scopes::Scope* scope, const std::function<void()>& perCombination);

  /**
   * @brief Visits the (optional) precondition/effect blocks shared by action and trigger bodies.
   *
   * @param preconditionCtx Precondition block context, or nullptr if not present.
   * @param effectCtx Effect block context, or nullptr if not present.
   * @param precondition Out param set to the visited precondition expression, if preconditionCtx isn't null.
   * @param effect Out param set to the visited effect expression, if effectCtx isn't null.
   */
  void assignPreconditionAndEffect(KasXParser::Precondition_blockContext* preconditionCtx,
                                   KasXParser::Effect_blockContext* effectCtx,
                                   DataStructures::Expressions::ExpressionPtr& precondition,
                                   DataStructures::Expressions::ExpressionPtr& effect);

  /**
   * @brief Resolves an action's consenting character list (if present) to entity declarations, applying the scope's replace
   * map first, and appends them to `consenting`.
   *
   * @param consentingListCtx Consenting list context, or nullptr if not present.
   * @param scope Scope used to resolve replaced identifiers.
   * @param consenting Out vector that resolved entities are appended to.
   */
  void assignConsentingCharacters(KasXParser::Consenting_listContext* consentingListCtx, Core::Scopes::Scope* scope,
                                  std::vector<DataStructures::Declarations::EntityDeclaration*>& consenting);

  /**
   * @brief Visits an action's observing function (if present), evaluating its expression once for a single bound observer or
   * once per entity of the observer's type, and appends the resulting expressions to `observations`.
   *
   * @param observingFuncCtx Observing function context, or nullptr if not present.
   * @param scope Scope used to bind the observer identifier while grounding over a type.
   * @param observations Out vector that visited observation expressions are appended to.
   */
  void assignObservations(KasXParser::Observing_funContext* observingFuncCtx, Core::Scopes::Scope* scope,
                          std::vector<DataStructures::Expressions::ExpressionPtr>& observations);

  // Visitor functionality for if else operatin
  void visitConditionalPart(KasXParser::ExprIfElseContext* ctx, size_t index,
                            DataStructures::Expressions::IfElseOperation* ifElseOperation);
  void visitPartIfElse(KasXParser::ExprIfElseContext* ctx, DataStructures::Expressions::IfElseOperation* ifElseOperation);
  void visitPartElse(KasXParser::ExprIfElseContext* ctx, size_t expressionIndex,
                     DataStructures::Expressions::IfElseOperation* ifElseOperation);
};
}  // namespace KasX::Compiler::Visitors
