/*
* File name: ProgramVisitor.hpp
* Project: KasX Compiler
* Author: Lasantha M Senanayake
* Date created: 2025-12-21 14:20:04
// Date modified: 2025-12-27 11:38:54
* ------
*/
#pragma once
#include <any>

#include "../core/logging/TraceableClass.hpp"
#include "AntlrSafeBase.hpp"
#include "KasXParser.h"
#include "kasx/Domain.hpp"

namespace KasX::Compiler::Visitors {
/**
 * @class ProgramVisitor
 * @brief This class will visit the domain context tree generated by antlr4 and port it to this custom visitor class to handle
 * build the domain in KasX compiler program.
 *
 * This class will handle all the visiting of the parse tree created by antlr4
 *
 */
class ProgramVisitor : public KasXBaseVisitor, public Core::TraceableClass {
 public:
  explicit ProgramVisitor(Core::Domain* domain);

  ~ProgramVisitor() override;

  /**
   * @brief Visitor function for the type declaration.
   *
   * @param ctx Type Declaration context
   */
  std::any visitTypeDeclaration(KasXParser::TypeDeclarationContext* ctx) override;

 private:
  Core::Domain* m_Domain;

  // ---- Printing messages (Trace)
  static void printStartVisit(std::string_view type, std::string_view identifier);

  static void printEndVisit(std::string_view type, std::string_view identifier);
};
}  // namespace KasX::Compiler::Visitors
